# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7ea0ecd1-ff9b-4601-aea5-dc801c0e2a76";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E8CD-2A06";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ 
      {
        device = "/var/lib/swapfile"; 
        size = 8*1024; # 8 GiB 
        priority = 10; # Higher number = higher priority
      }
      { 
        device = "/dev/disk/by-uuid/ed7cc9bc-52e9-49f8-8f8c-a67ce178425a"; 
        priority = 10; # If priorities match, it balances between them
      }
    ];
}
