# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, inputs, ... }:

{
  fileSystems."/" =
    { device = "/dev/disk/by-label/NIXOS_ROOT";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXOS_BOOT";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =[
    {
      device = "/var/lib/swapfile"; 
      size = 8*1024; # 8 GiB 
      priority = 10; # Higher number = higher priority
    }
    {
      device = "/dev/disk/by-label/NIXOS_SWAP";
      priority = 10; # If priorities match, it balances between them
    }
  ];
}
