name: Test Default System build

on: [push, pull_request]

jobs:
  test-default-system-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: mySystem
            os: ubuntu-latest
          - host: nixos-install
            os: ubuntu-latest
            
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check nix flakes
        run: nix flake check 

      - name: Build default system derivation
        run: |
          nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel \
            --extra-experimental-features "nix-command flakes" \
            --print-build-logs \
            --show-trace