name: Test minimal-iso build

on: [push, pull_request]

jobs:
  test-minimal-iso-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check nix flakes
        run: nix flake check 
        
      - name: Build minimal-iso system derivation
        # Targets your packages.x86_64-linux.minimal-iso attribute
        run: nix build .#minimal-iso