name: Test nix-darwin build

on: [push, pull_request]

jobs:
  test-nix-darwin-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Check nix flakes
        run: nix flake check --extra-deprecated-features or-as-identifier

      - name: Build darwin system derivation
        # Targets your darwinConfigurations.<name>.system attribute
        run: nix build .#darwinConfigurations.darwinSystem.system