name: Test darwin build

on: [push, pull_request]

jobs:
  test-macos-flake:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build darwin system derivation
        # Targets your darwinConfigurations.<name>.system attribute
        run: nix build .#darwinConfigurations.macos